print('python is so magic')
print('python is so magic')
print('python is so magic')
print('python is so magic')
print('python is itcast')
print('python is itcast')
print('python is itcast')
print('python is itcast')
